packages:
  - .

catalogMode: manual

engineStrict: true

hoist: false

ignoreDepScripts: true

minimumReleaseAge: 10800

minimumReleaseAgeExclude:
  - '@bbc/*'
  - '@ibl/*'

overrides:
  debug@>=3.2.0 <3.2.7: '>=3.2.7'
  flat@<5.0.1: '>=5.0.1'
  form-data@<2.5.4: '>=2.5.4'
  js-yaml@<3.14.2: '>=3.14.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  minimatch@<3.0.5: '>=3.0.5'
  tough-cookie@<4.1.3: '>=4.1.3'
  flat: "5.0.2"

publicHoistPattern:
  - eslint-*
  - '@eslint/*'
  - '@typescript-eslint/*'
  - jest
  - taffydb

recursiveInstall: false

sharedWorkspaceLockfile: false
